# Generated by Django 4.2.3 on 2024-03-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
