# Generated by Django 4.2.3 on 2024-04-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='evid',
            field=models.IntegerField(null=True),
        ),
    ]
