# Generated by Django 5.1.7 on 2025-03-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_evid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='first_name',
        ),
    ]
